version: "3.9"

services:
  optiasset_app:
    container_name: optiasset_app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - optiasset_db
    restart: always

volumes:
  optiasset_mysql_data:
